/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoclinicadental;

import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class frmDentistas extends javax.swing.JFrame {

    /**
     * Creates new form frmDentistas
     */
    public frmDentistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDatosDentista = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDatosDentista.setText("DATOS DEL DENTISTA");
        getContentPane().add(lblDatosDentista, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 16, 160, 30));

        jLabel1.setText("NOMBRES:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, 30));

        jLabel2.setText("APELLIDOS:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 30));

        jLabel3.setText("DUI:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 40, 30));

        jLabel4.setText("NIT:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 50, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 250, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 250, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 130, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 130, -1));

        jLabel7.setText("DIRECCION:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 310, -1));

        jLabel8.setText("TELEFONO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 70, 20));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 150, -1));

        jButton1.setText("ATRAS");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jButton2.setText("AGREGAR");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarCliente() {
        class_Medicos med=new class_Medicos();
        med.insertar(jTextField1.getText(), jTextField2.getText(),jTextField6.getText(), jTextField5.getText(), jTextField3.getText(), jTextField4.getText());
        Mensajes("El registro del nuevo cliente se ha logrado con éxito");
    }
    private void Mensajes(String Men){
        JOptionPane.showMessageDialog(this, Men);
    }
    private void comprobarcampos(){
        String mens="";
        if(jTextField1.getText().isEmpty())
            mens=("No ha ingresado el nombre\n");
        if(jTextField2.getText().isEmpty())
            mens+=("No ha ingresado apellidos\n");
        if(jTextField3.getText().isEmpty())
            mens+=("No ha ingresado DUI\n");
        if(jTextField4.getText().isEmpty())
            mens+=("No ha ingresado NIT\n");
        if(jTextField5.getText().isEmpty())
            mens+=("No ha ingresado dirección\n");
        if(jTextField6.getText().isEmpty())
            mens+=("No ha ingresado teléfono\n");
        
        if(!mens.equals(""))
            Mensajes(mens);
        else 
            RegistrarCliente();
        mens="";
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        comprobarcampos();
    }                                        

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {                                     
        if(jTextField1.getText().length()==50)
            evt.consume();
        if(!Character.isLetter(evt.getKeyChar()))
            evt.consume();
    }                                    

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {                                     
        if(jTextField2.getText().length()==50)
            evt.consume();
        if(!Character.isLetter(evt.getKeyChar()))
            evt.consume();
    }                                    

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {                                     
        if(jTextField3.getText().length()==10)
            evt.consume();
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }                                    

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {                                     
        if(jTextField4.getText().length()==15)
            evt.consume();
        if((!Character.isDigit(evt.getKeyChar()))&&(!Character.isLetter(evt.getKeyChar())))
            evt.consume();
    }                                    

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {                                     
        if(jTextField5.getText().length()==100)
            evt.consume();
    }                                    

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {                                     
        if(jTextField6.getText().length()==8)
            evt.consume();
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }                                    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        frmMenuPrincipal menu=new frmMenuPrincipal();
        this.dispose();
        menu.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDentistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDentistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDentistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDentistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDentistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblDatosDentista;
    // End of variables declaration//GEN-END:variables
}
