/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectoclinicadental;

/**
 *
 * @author Javier
 */
public class frmFacturacion extends javax.swing.JFrame {

    /** Creates new form frmFacturacion */
    public frmFacturacion() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFacturacion = new javax.swing.JLabel();
        lblFechaFactura = new javax.swing.JLabel();
        txtFechaFactura = new javax.swing.JTextField();
        lblHoraFactura = new javax.swing.JLabel();
        txtHoraFactura = new javax.swing.JTextField();
        lblCitaFactura = new javax.swing.JLabel();
        cmbCitaFactura = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmbHistorialCFactura = new javax.swing.JComboBox<>();
        lblCostoFactura = new javax.swing.JLabel();
        txtCostoFactura = new javax.swing.JTextField();
        lblDetallesFactura = new javax.swing.JLabel();
        txtDetallesFactura = new javax.swing.JTextField();
        btnAgregarFactura = new javax.swing.JButton();
        btnAtrasFactura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFacturacion.setText("FACTURACION");
        getContentPane().add(lblFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 25, -1, -1));

        lblFechaFactura.setText("Fecha:");
        getContentPane().add(lblFechaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 73, -1, -1));
        getContentPane().add(txtFechaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 67, 105, -1));

        lblHoraFactura.setText("Hora:");
        getContentPane().add(lblHoraFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 73, -1, -1));
        getContentPane().add(txtHoraFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 67, 95, -1));

        lblCitaFactura.setText("Cita:");
        getContentPane().add(lblCitaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 132, -1, -1));

        cmbCitaFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCitaFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 127, 144, -1));

        jLabel5.setText("Historial de Cliente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 182, -1, -1));

        cmbHistorialCFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbHistorialCFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 129, -1));

        lblCostoFactura.setText("Costo:");
        getContentPane().add(lblCostoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 235, -1, -1));
        getContentPane().add(txtCostoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 229, 93, -1));

        lblDetallesFactura.setText("Otros Detalles:");
        getContentPane().add(lblDetallesFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 286, -1, -1));
        getContentPane().add(txtDetallesFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 224, -1));

        btnAgregarFactura.setText("AGREGAR");
        getContentPane().add(btnAgregarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 353, -1, -1));

        btnAtrasFactura.setText("ATRAS");
        getContentPane().add(btnAtrasFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 353, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fundo-azul-da-tecnologia-com-linhas_23-2147611285.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarFactura;
    private javax.swing.JButton btnAtrasFactura;
    private javax.swing.JComboBox<String> cmbCitaFactura;
    private javax.swing.JComboBox<String> cmbHistorialCFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCitaFactura;
    private javax.swing.JLabel lblCostoFactura;
    private javax.swing.JLabel lblDetallesFactura;
    private javax.swing.JLabel lblFacturacion;
    private javax.swing.JLabel lblFechaFactura;
    private javax.swing.JLabel lblHoraFactura;
    private javax.swing.JTextField txtCostoFactura;
    private javax.swing.JTextField txtDetallesFactura;
    private javax.swing.JTextField txtFechaFactura;
    private javax.swing.JTextField txtHoraFactura;
    // End of variables declaration//GEN-END:variables

}
