/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoclinicadental;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class frmTratamientosOdontologicos extends javax.swing.JFrame {

    /**
     * Creates new form frmTratamientosOdontologicos
     */
    
    class_TratamientosDentDisponibles trat=new class_TratamientosDentDisponibles();
    ResultSet rst_lista=null;  
    DefaultListModel modelo=new DefaultListModel();
    public frmTratamientosOdontologicos() {
        initComponents();
        llenarlista();
        txtTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        lblTemaTratamientos.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        lblTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        lstTratamientos.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        btnAgregarTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
        btnAtrasTratamiento.setFont(new java.awt.Font("Times New Roman", 0, 20)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTemaTratamientos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTratamientos = new javax.swing.JList<>();
        lblTratamiento = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        btnAgregarTratamiento = new javax.swing.JButton();
        btnAtrasTratamiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTemaTratamientos.setText("TRATAMIENTOS ODONTOLOGICOS");

        jScrollPane1.setViewportView(lstTratamientos);

        lblTratamiento.setText("Añadir tratamiento:");

        txtTratamiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTratamientoKeyTyped(evt);
            }
        });

        btnAgregarTratamiento.setText("AGREGAR");
        btnAgregarTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTratamientoActionPerformed(evt);
            }
        });

        btnAtrasTratamiento.setText("ATRAS");
        btnAtrasTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasTratamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTemaTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(lblTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(90, 90, 90)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAgregarTratamiento)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAtrasTratamiento))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTemaTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtrasTratamiento)
                    .addComponent(btnAgregarTratamiento))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTratamientoActionPerformed
        if(txtTratamiento.getText().length()>4){
            trat.insertar(txtTratamiento.getText());
            JOptionPane.showMessageDialog(this, "Nuevo tratamiento registrado con éxito");
        }else
            JOptionPane.showMessageDialog(this, "No hay un dato representativo del tratamiento");
        llenarlista();
    }//GEN-LAST:event_btnAgregarTratamientoActionPerformed

    private void btnAtrasTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasTratamientoActionPerformed
            frmMenuPrincipal menu=new frmMenuPrincipal();
            this.dispose();
            menu.setVisible(true);
    }//GEN-LAST:event_btnAtrasTratamientoActionPerformed

    private void txtTratamientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTratamientoKeyTyped
        if(txtTratamiento.getText().length()==100)
            evt.consume();
    }//GEN-LAST:event_txtTratamientoKeyTyped

    private void llenarlista(){        
        try{
            modelo.removeAllElements();
            rst_lista=trat.ListaTratamientos();
            while (rst_lista.next()) 
                modelo.addElement(rst_lista.getString(1).toString());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", 0);
                modelo.addElement("Error");
        }
        lstTratamientos.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTratamientosOdontologicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTratamientosOdontologicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTratamientosOdontologicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTratamientosOdontologicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTratamientosOdontologicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTratamiento;
    private javax.swing.JButton btnAtrasTratamiento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTemaTratamientos;
    private javax.swing.JLabel lblTratamiento;
    private javax.swing.JList<String> lstTratamientos;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
